image_width: 1280
image_height: 1024
camera_name: mv_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [2072.29837,    0.     ,  710.12268,
            0.     , 2081.51006,  361.59642,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.017770, -0.160367, -0.011223, 0.005580, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2067.34665,    0.     ,  714.57387,    0.     ,
            0.     , 2070.19278,  361.59642,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
